export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_COUNT = 'SET_COUNT'
export const SET_FORM = 'SET_FORM'
export const SET_LIST = 'SET_LIST'
export const SET_APP = 'SET_APP'
export const SET_CONTEXTUAL = 'SET_CONTEXTUAL'
export const SHOULD_CLOSE = 'SHOULD_CLOSE'
